# Resumen:
# 
# Este proyecto está compuesto por varios servicios: una base de datos MySQL, un frontend en Vue.js, un backend en Laravel.
# Cada servicio está definido en su respectiva sección de Docker Compose.
# 
# Para ejecutar el proyecto:
#
# 1. Asegúrate de tener Docker y Docker Compose instalados en tu máquina.
# 2. Una vez que los contenedores estén en ejecución, sigue estos pasos:
#
#   - Para instalar las dependencias de Laravel:
#
#     1. Navega a la carpeta `back/laravel` y ejecuta `composer install`.
#
#    - Para iniciar la aplicación, escribe en la terminal `docker-compose up`.
# 
# Los servicios estarán disponibles en los siguientes puertos:
# - Frontend (Vue.js): http://localhost:5173
# - Backend (Laravel): http://localhost:8000
# - Adminer (gestor de base de datos MySQL): http://localhost:9092

services:
  db:
    image: mysql:8.2.0  
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root  # Solo esta línea para el usuario root
      MYSQL_DATABASE: delidelishare
      # Eliminé MYSQL_USER y MYSQL_PASSWORD ya que causan conflicto con root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer  
    restart: always 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9094:8080  

  vue-app:
    build: ./front
    working_dir: /app  
    volumes:
      - ./front:/app  
      - /app/node_modules   
    ports:
      - "5173:5173" 
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy

  laravel:
    build: ./back
    volumes:
      - ./back:/var/www/html  
    working_dir: /var/www/html  
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=delidelishare
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"  
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "composer install && php artisan key:generate && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  mysql_data: